# Site settings

title: Hamed Mehryar # Title of your site
email: hamed.cs@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  This is my website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     hamedmehryar  # Replace this with your Twitter username
github_username:      hamedmehryar  # Replace this with your GitHub username
linkedin_username:    hamed-mehryar-4b0a1387  # Replace this with your LinkedIn username
facebook_username:    hamedmehryar  # Replace this with your Facebook username

# Build settings
markdown: kramdown
